CREATE USER dariae WITH ENCRYPTED PASSWORD 'dariae';
GRANT ALL PRIVILEGES ON DATABASE beautyoutlet TO dariae;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dariae;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dariae;